// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS_0rWMlCeRfLeIEkydSlZ0Vy8V6IVbZ0',
    appId: '1:756689813454:web:05820488546593776f759f',
    messagingSenderId: '756689813454',
    projectId: 'smarthumidifier-9fd06',
    authDomain: 'smarthumidifier-9fd06.firebaseapp.com',
    databaseURL: 'https://smarthumidifier-9fd06-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smarthumidifier-9fd06.firebasestorage.app',
    measurementId: 'G-YN299CTTFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoGqah13VDgpAP5iFAMwW-O8sDBog4mZ0',
    appId: '1:756689813454:android:2d20612b7fb523e46f759f',
    messagingSenderId: '756689813454',
    projectId: 'smarthumidifier-9fd06',
    databaseURL: 'https://smarthumidifier-9fd06-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smarthumidifier-9fd06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvKaEBQKMGBxgGVTFJ1KdL-1vOI_NGzRc',
    appId: '1:756689813454:ios:45bab0f804193a3b6f759f',
    messagingSenderId: '756689813454',
    projectId: 'smarthumidifier-9fd06',
    databaseURL: 'https://smarthumidifier-9fd06-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smarthumidifier-9fd06.firebasestorage.app',
    iosBundleId: 'com.example.humidifierApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvKaEBQKMGBxgGVTFJ1KdL-1vOI_NGzRc',
    appId: '1:756689813454:ios:45bab0f804193a3b6f759f',
    messagingSenderId: '756689813454',
    projectId: 'smarthumidifier-9fd06',
    databaseURL: 'https://smarthumidifier-9fd06-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smarthumidifier-9fd06.firebasestorage.app',
    iosBundleId: 'com.example.humidifierApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS_0rWMlCeRfLeIEkydSlZ0Vy8V6IVbZ0',
    appId: '1:756689813454:web:dde64c4b066fe0146f759f',
    messagingSenderId: '756689813454',
    projectId: 'smarthumidifier-9fd06',
    authDomain: 'smarthumidifier-9fd06.firebaseapp.com',
    databaseURL: 'https://smarthumidifier-9fd06-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smarthumidifier-9fd06.firebasestorage.app',
    measurementId: 'G-QFCJW9RYT3',
  );
}
